version: "3.8"

services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app-prod
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
